server:
  port: 11000
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos/
    routes:
      - name: 乐曲查询
        serviceName: music-service
        location: /v2/api-docs
        servicePath: /api
        swaggerVersion: 3.0
